### 查询单条
GET http://localhost:9200/imooc/cource/1

### 添加数据 (PUT)
PUT http://localhost:9200/imooc/cource/3
Content-Type: application/json

{"name": "C++","instructor": "ccmouse"}

### 添加数据 (POST)
POST http://localhost:9200/imooc/cource/4
Content-Type: application/json

{"name": "php","instructor": "ccmouse"}

### 查询所有
GET http://localhost:9200/imooc/cource/_search

### 带条件查询
GET http://localhost:9200/imooc/cource/_search?q=ccmouse

### 自动格式化 pretty=true
GET http://localhost:9200/imooc/cource/_search?pretty=true

### 添加数据 （不加ID必须使用POST）
POST http://localhost:9200/imooc/cource/
Content-Type: application/json

{"name": "golang_pipeline", "instructor": "ccmouse","url": "https://www.imooc.com"}

###
GET http://localhost:9200/imooc/cource/_search

### 对已有数据添加属性
PUT http://localhost:9200/imooc/cource/3
Content-Type: application/json

{"name": "python","instructor": "ccmouse","url": "http://www.imooc.com/python"}

###
GET http://localhost:9200/imooc/cource/_mapping

###
GET http://localhost:9200/dating_profile/zhenai/_search

###
POST http://localhost:9200/imooc/cource
Content-Type: application/json

{"baseInfo":["离异","37岁","天蝎座(10.23-11.21)","160cm","51kg","工作地:阿坝马尔康","月收入:3-5千","小学教师","大学本科"]}

###
POST http://localhost:9200/imooc/cource
Content-Type: application/json

{"baseInfo":["未婚","25岁","魔羯座(12.22-01.19)","165cm","51kg","工作地:上海浦东新区","月收入:8千-1.2万","教育\u002F科研","大学本科"]}

###

###
GET http://localhost:9200/imooc/cource/_search?q="37岁"

###
GET http://localhost:9200/dating_profile/zhenai/_search?size=2

###
GET http://localhost:9200/dating_profile/zhenai/_search?q=大学本科 离异 Age:(<26)&pretty=true

###
GET http://localhost:9200/dating_profile/zhenai/1769167712

###
GET http://localhost:9200/dating_test/zhenai/_search

###
GET http://localhost:9200

###
