// Code generated by protoc-gen-go. DO NOT EDIT.
// source: toupper.proto

package protc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpperReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpperReq) Reset()         { *m = UpperReq{} }
func (m *UpperReq) String() string { return proto.CompactTextString(m) }
func (*UpperReq) ProtoMessage()    {}
func (*UpperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9263bae945d71a4, []int{0}
}

func (m *UpperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpperReq.Unmarshal(m, b)
}
func (m *UpperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpperReq.Marshal(b, m, deterministic)
}
func (m *UpperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpperReq.Merge(m, src)
}
func (m *UpperReq) XXX_Size() int {
	return xxx_messageInfo_UpperReq.Size(m)
}
func (m *UpperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpperReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpperReq proto.InternalMessageInfo

func (m *UpperReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpperResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpperResp) Reset()         { *m = UpperResp{} }
func (m *UpperResp) String() string { return proto.CompactTextString(m) }
func (*UpperResp) ProtoMessage()    {}
func (*UpperResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9263bae945d71a4, []int{1}
}

func (m *UpperResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpperResp.Unmarshal(m, b)
}
func (m *UpperResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpperResp.Marshal(b, m, deterministic)
}
func (m *UpperResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpperResp.Merge(m, src)
}
func (m *UpperResp) XXX_Size() int {
	return xxx_messageInfo_UpperResp.Size(m)
}
func (m *UpperResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpperResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpperResp proto.InternalMessageInfo

func (m *UpperResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UpperReq)(nil), "protc.UpperReq")
	proto.RegisterType((*UpperResp)(nil), "protc.UpperResp")
}

func init() { proto.RegisterFile("toupper.proto", fileDescriptor_b9263bae945d71a4) }

var fileDescriptor_b9263bae945d71a4 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc9, 0x2f, 0x2d,
	0x28, 0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x51, 0xc9, 0x4a, 0x72,
	0x5c, 0x1c, 0xa1, 0x20, 0xd1, 0xa0, 0xd4, 0x42, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x95, 0x8b, 0x13, 0x2a, 0x5f, 0x5c,
	0x20, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x0e, 0x53, 0x03, 0xe3, 0x1a, 0x99,
	0x73, 0xb1, 0x87, 0xe4, 0x83, 0x15, 0x0a, 0xe9, 0x70, 0xb1, 0x42, 0x18, 0xfc, 0x60, 0x9b, 0x92,
	0xf5, 0x60, 0xe6, 0x4b, 0x09, 0xa0, 0x0a, 0x14, 0x17, 0x28, 0x31, 0x24, 0xb1, 0x81, 0x5d, 0x63,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x66, 0x12, 0xd3, 0x9e, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToUpperClient is the client API for ToUpper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToUpperClient interface {
	Upper(ctx context.Context, in *UpperReq, opts ...grpc.CallOption) (*UpperResp, error)
}

type toUpperClient struct {
	cc *grpc.ClientConn
}

func NewToUpperClient(cc *grpc.ClientConn) ToUpperClient {
	return &toUpperClient{cc}
}

func (c *toUpperClient) Upper(ctx context.Context, in *UpperReq, opts ...grpc.CallOption) (*UpperResp, error) {
	out := new(UpperResp)
	err := c.cc.Invoke(ctx, "/protc.ToUpper/Upper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToUpperServer is the server API for ToUpper service.
type ToUpperServer interface {
	Upper(context.Context, *UpperReq) (*UpperResp, error)
}

// UnimplementedToUpperServer can be embedded to have forward compatible implementations.
type UnimplementedToUpperServer struct {
}

func (*UnimplementedToUpperServer) Upper(ctx context.Context, req *UpperReq) (*UpperResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upper not implemented")
}

func RegisterToUpperServer(s *grpc.Server, srv ToUpperServer) {
	s.RegisterService(&_ToUpper_serviceDesc, srv)
}

func _ToUpper_Upper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpperReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToUpperServer).Upper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protc.ToUpper/Upper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToUpperServer).Upper(ctx, req.(*UpperReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToUpper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protc.ToUpper",
	HandlerType: (*ToUpperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upper",
			Handler:    _ToUpper_Upper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "toupper.proto",
}
